# This is instruction for building container images
# Use PHP 7.2 as base image
FROM php:7.2-fpm

# Install system dependencies
RUN apt-get update -qq && \
    apt-get install -y -f -qq \
    zip \
    git \
    build-essential && \
    rm -rf /var/lib/apt/lists/*

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the working directory inside the container
WORKDIR /var/www

# Copy the Laravel project files into the container
COPY . .

# Install dependencies (if you have a composer.json)
RUN composer install

# Expose port 9000 to be accessed from outside
EXPOSE 9000

# Start PHP-FPM
CMD ["php-fpm"]
